### ISSUE TITLE
vector-0.13 not allowed

### ISSUE THREAD

**Issue by ysangkok** [leptonyu/tensors#14]
Allowing this version would allow tensors to remain in Stackage when the upgrade is made. See

* https://github.com/commercialhaskell/stackage/issues/6624

**Comment by leptonyu** [comment]
Hi @ysangkok , I updated version for https://hackage.haskell.org/package/tensors-0.1.5.

**Comment by ysangkok** [comment]
@leptonyu The test suite still needs a bounds update: https://github.com/commercialhaskell/stackage/actions/runs/4909236128/jobs/8765516822?pr=6969

**Comment by leptonyu** [comment]
@ysangkok Sorry, I didn't notice it. Updated
